//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dapr.PluggableComponents {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dapr.PluggableComponents.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete affected {0} rows, but expected {1}..
        /// </summary>
        internal static string BulkDeleteRowMismatchExceptionMessage {
            get {
                return ResourceManager.GetString("BulkDeleteRowMismatchExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ETag value..
        /// </summary>
        internal static string ETagInvalidExceptionMessage {
            get {
                return ResourceManager.GetString("ETagInvalidExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible ETag mismatch..
        /// </summary>
        internal static string ETagMismatchExceptionMessage {
            get {
                return ResourceManager.GetString("ETagMismatchExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The component expects at least one request..
        /// </summary>
        internal static string PubSubAdaptorPullExpectsRequestMessage {
            get {
                return ResourceManager.GetString("PubSubAdaptorPullExpectsRequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The component expects the first request to specify the topic..
        /// </summary>
        internal static string PubSubAdaptorPullExpectsTopicMessage {
            get {
                return ResourceManager.GetString("PubSubAdaptorPullExpectsTopicMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sorting order &apos;{0}&apos; was not recognized..
        /// </summary>
        internal static string StateStoreQuerySortingUnrecognizedOrderMessage {
            get {
                return ResourceManager.GetString("StateStoreQuerySortingUnrecognizedOrderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The concurrency &apos;{0}&apos; was not recognized..
        /// </summary>
        internal static string StateStoreStateOptionsUnrecognizedConcurrencyMessage {
            get {
                return ResourceManager.GetString("StateStoreStateOptionsUnrecognizedConcurrencyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The consistency &apos;{0}&apos; was not recognized..
        /// </summary>
        internal static string StateStoreStateOptionsUnrecognizedConsistencyMessage {
            get {
                return ResourceManager.GetString("StateStoreStateOptionsUnrecognizedConsistencyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation &apos;{0}&apos; is not recognized..
        /// </summary>
        internal static string StateStoreTransactOperationUnrecognizedMessage {
            get {
                return ResourceManager.GetString("StateStoreTransactOperationUnrecognizedMessage", resourceCulture);
            }
        }
    }
}
