//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dapr.PluggableComponents.AspNetCore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dapr.PluggableComponents.AspNetCore.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The component provider type &apos;{0}&apos; was already registered with socket &apos;{1}&apos;..
        /// </summary>
        internal static string DaprPluggableComponentsRegistryDuplicateTypeMessage {
            get {
                return ResourceManager.GetString("DaprPluggableComponentsRegistryDuplicateTypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No component provider was registered for type &apos;{0}&apos;..
        /// </summary>
        internal static string DaprPluggableComponetnsRegistryProviderNotFoundMessage {
            get {
                return ResourceManager.GetString("DaprPluggableComponetnsRegistryProviderNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to obtain a provider for component type &apos;{0}&apos;..
        /// </summary>
        internal static string RegisteredComponentProviderNoProviderMessage {
            get {
                return ResourceManager.GetString("RegisteredComponentProviderNoProviderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine the socket on which a gRPC request was made..
        /// </summary>
        internal static string RegisteredComponentProviderUnknownSocketMessage {
            get {
                return ResourceManager.GetString("RegisteredComponentProviderUnknownSocketMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A service was already added at socket path &apos;{0}&apos;..
        /// </summary>
        internal static string WebApplicationBuilderExtensionsDuplicateSocketMessage {
            get {
                return ResourceManager.GetString("WebApplicationBuilderExtensionsDuplicateSocketMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid socket extension was specified via options or environment variable..
        /// </summary>
        internal static string WebApplicationBuilderExtensionsNoExtensionMessage {
            get {
                return ResourceManager.GetString("WebApplicationBuilderExtensionsNoExtensionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid socket folder was specified via options or environment variable..
        /// </summary>
        internal static string WebApplicationBuilderExtensionsNoFolderMessage {
            get {
                return ResourceManager.GetString("WebApplicationBuilderExtensionsNoFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid socket name was specified via options or environment variable..
        /// </summary>
        internal static string WebApplicationBuilderExtensionsNoSocketNameMessage {
            get {
                return ResourceManager.GetString("WebApplicationBuilderExtensionsNoSocketNameMessage", resourceCulture);
            }
        }
    }
}
